importArticle({type:'script',article:'u:dev:MediaWiki:AjaxRC.js'});;window.DiscordChat={ready:!1,messages:{},data:null,init:function(){window.DiscordChat.ready=!0
var mwconfig=mw.config.get(['wgUserLanguage'])
var api=new mw.Api()
api.get({action:'query',meta:'allmessages',ammessages:['chat-live2','chat-join-the-chat','awc-metrics-close','chat-entry-point-guidelines','Custom-DiscordChat-id'].join('|'),amlang:mwconfig.wgUserLanguage}).done(function(data){if(data.error){return}data.query.allmessages.forEach(function(message){if(message['*']){window.DiscordChat.messages[message.name]=_.escape(message['*'])}})
if(window.DiscordChat.messages['chat-entry-point-guidelines']){api.get({action:'parse',text:'{{int:chat-entry-point-guidelines}}',prop:'text'}).done(function(data){mw.hook('DiscordChat.added').add(function(){$('<div>',{'class':'more'}).html(data.parse.text['*']).appendTo('.DiscordChat')})})}$.get('https://discordapp.com/api/guilds/'+window.DiscordChat.messages['Custom-DiscordChat-id']+'/widget.json',function(data){window.DiscordChat.data=data
if($('#WikiaRail').length){if($('#WikiaRail').hasClass('loaded')){window.DiscordChat.rail()}else{$('#WikiaRail').on('afterLoad.rail',window.DiscordChat.rail)}}})})},rail:function(){var i=0
var appendedAvatars=0
var avatarContainer=$('<div class="wds-avatar-stack"></div>')
var members=window.DiscordChat.data.members
window.DiscordChat.shuffle(members)
while(appendedAvatars<5&&i<members.length){if(!members[i].bot){avatarContainer.append('<a href="#showDiscordUser" data-discorduser="'+encodeURI(_.escape(members[i].username+'#'+members[i].discriminator))+'" class="wds-avatar chatter"><img class="wds-avatar__image" src="'+members[i].avatar_url+'"></a>')
appendedAvatars++}i++}var element=$('<section class="chat-module rail-module DiscordChat">'+'<h2 class="has-icon">'+
'<svg xmlns="http://www.w3.org/2000/svg" class="discord-svg" width="20" height="20" viewBox="0 0 240 245"><path d="M104.4 103.9c-5.7 0-10.2 5-10.2 11.1s4.6 11.1 10.2 11.1c5.7 0 10.2-5 10.2-11.1.1-6.1-4.5-11.1-10.2-11.1zM140.9 103.9c-5.7 0-10.2 5-10.2 11.1s4.6 11.1 10.2 11.1c5.7 0 10.2-5 10.2-11.1s-4.5-11.1-10.2-11.1z"/><path d="M189.5 20h-134C44.2 20 35 29.2 35 40.6v135.2c0 11.4 9.2 20.6 20.5 20.6h113.4l-5.3-18.5 12.8 11.9 12.1 11.2 21.5 19V40.6c0-11.4-9.2-20.6-20.5-20.6zm-38.6 130.6s-3.6-4.3-6.6-8.1c13.1-3.7 18.1-11.9 18.1-11.9-4.1 2.7-8 4.6-11.5 5.9-5 2.1-9.8 3.5-14.5 4.3-9.6 1.8-18.4 1.3-25.9-.1-5.7-1.1-10.6-2.7-14.7-4.3-2.3-.9-4.8-2-7.3-3.4-.3-.2-.6-.3-.9-.5-.2-.1-.3-.2-.4-.3-1.8-1-2.8-1.7-2.8-1.7s4.8 8 17.5 11.8c-3 3.8-6.7 8.3-6.7 8.3-22.1-.7-30.5-15.2-30.5-15.2 0-32.2 14.4-58.3 14.4-58.3 14.4-10.8 28.1-10.5 28.1-10.5l1 1.2c-18 5.2-26.3 13.1-26.3 13.1s2.2-1.2 5.9-2.9c10.7-4.7 19.2-6 22.7-6.3.6-.1 1.1-.2 1.7-.2 6.1-.8 13-1 20.2-.2 9.5 1.1 19.7 3.9 30.1 9.6 0 0-7.9-7.5-24.9-12.7l1.4-1.6s13.7-.3 28.1 10.5c0 0 14.4 26.1 14.4 58.3 0 0-8.5 14.5-30.6 15.2z"/></svg>'
+window.DiscordChat.messages['chat-live2']+' – Discord'+'</h2>'+'<div class="chat-details">'+'<div class="avatars">'+avatarContainer.prop('outerHTML')+((members.length-appendedAvatars)>0?('<a href="'+'#showDiscordUsers'+'" style="font-weight: bold; margin-left: 6px; text-decoration: none;">+'+(members.length-appendedAvatars)+'</a>'):'')+'</div>'+'<a href="'+window.DiscordChat.data.instant_invite+'" class="wds-is-secondary wds-button wds-is-squished">'+window.DiscordChat.messages['chat-join-the-chat']+'</a>'+'</div>'+'</section>')
$ads=$('#top-right-boxad-wrapper, #NATIVE_TABOOLA_RAIL').last(),$jsrt=$('.content-review-module');if($ads.exists()){$ads.after(element);}else if($jsrt.exists()){$jsrt.after(element);}else{$('#WikiaRail').prepend(element);}$('.chat-module:not(.DiscordChat)').css('display','none')
mw.util.addCSS('#WikiaRail .DiscordChat .wds-avatar-stack { z-index: 0; }');$('a[href="#showDiscordUser"][data-discorduser]').click(function(event){event.preventDefault()
window.DiscordChat.showDiscordUser(decodeURI($(this).attr('data-discorduser')))})
$('a[href="#showDiscordUsers"]').click(function(event){event.preventDefault()
window.DiscordChat.showDiscordUsers()})
mw.hook('DiscordChat.added').fire(element)},showDiscordUsers:function(){var usersContent='<ul style="list-style: initial; font-size: 14px;">'
var members=window.DiscordChat.data.members
for(var i=0;i<members.length;i++){usersContent+='<li><span style="-moz-user-select: none; user-select: none; cursor: pointer;" onclick="window.DiscordChat.showDiscordUser(\''+_.escape(members[i].username+'#'+members[i].discriminator)+'\');"><img style="width: 0.75em; height: 0.75em;" src="'+members[i].avatar_url+'"> '+_.escape(members[i].nick||members[i].username)+'</span></li>'}usersContent+='</ul>'
require(['wikia.ui.factory'],function(ui){ui.init(['modal']).then(function(uimodal){var modalconfig={type:'default',vars:{id:'show-discord-users',size:'small',title:_.escape(window.DiscordChat.data.name)+' – '+window.DiscordChat.data.members.length,content:usersContent,buttons:[{vars:{value:window.DiscordChat.messages['awc-metrics-close'],data:[{key:'event',value:'close'}]}},{type:'link',vars:{value:window.DiscordChat.messages['chat-join-the-chat'],href:window.DiscordChat.data.instant_invite,title:''}}]}}
uimodal.createComponent(modalconfig,function(modal){modal.show()})})})},showDiscordUser:function(tag){var members=window.DiscordChat.data.members
var mi=null
for(var i=0;i<members.length;i++){if(members[i].username+'#'+members[i].discriminator===tag){mi=i
break}}require(['wikia.ui.factory'],function(ui){ui.init(['modal']).then(function(uimodal){var modalconfig={type:'default',vars:{id:'show-discord-user',size:'small',title:_.escape(members[mi].nick||members[mi].username)+(members[mi].bot?'&nbsp;[BOT]':''),content:'<center><div style="position: relative; width: 128px; height: 128px;"><img width="128" height="128" style="border-radius: 50%;" src="'+members[mi].avatar_url+'"><div style="position: absolute; width: 32px; height: 32px; border-radius: 50%; right: 0; bottom: 0; background-color: '+(members[mi].status==='online'?'lawngreen':(members[mi].status==='idle'?'gold':'firebrick'))+';"></div></div><br>'+_.escape(tag)+'</center>',buttons:[{vars:{value:window.DiscordChat.messages['awc-metrics-close'],data:[{key:'event',value:'close'}]}}]}}
uimodal.createComponent(modalconfig,function(modal){modal.show()})})})},shuffle:function(a){var j,x,i
for(i=a.length-1;i>0;i--){j=Math.floor(Math.random()*(i+1))
x=a[i]
a[i]=a[j]
a[j]=x}}}
mw.loader.using('mediawiki.api',function(){$(function(){if(window.DiscordChat&&!window.DiscordChat.ready){window.DiscordChat.init()}})});if(mediaWiki.config.get('wgAction')==='view')(function(){'use strict';var data_template;function createSlider(){var scrollPane=$(this),scrollPaneWidth=scrollPane.width(),scrollContent=scrollPane.find('.scroll-content'),scrollContentWidth=0,data_startPos=defaultValue(scrollContent.data("startpos"),0);data_template=defaultValue(scrollContent.data("template"),"GameSlider/Content");scrollContent.find('img').each(function(){var $this=$(this),width=$this.width();if(width){scrollContentWidth+=width;}else{$this.on('load',function(){scrollContentWidth+=$this.width();});}var img_link=$this.parent();var param=img_link.attr("href").substr(1);img_link.attr("href","javascript:void(0)");img_link.click(function(){createContent(param);$(".content-active").removeClass("content-active");$(this).addClass("content-active");});});var scrollbar=scrollPane.find('.scroll-bar'
).slider({value:data_startPos,slide:function(event,ui){if(scrollContentWidth>scrollPaneWidth){scrollContent.css('margin-left',Math.round(ui.value/100*(scrollPaneWidth-scrollContentWidth))+'px');}else{scrollContent.css('margin-left',0);}}});scrollPane.css("overflow","hidden");if(scrollContentWidth>scrollPaneWidth){scrollContent.css('margin-left',Math.round(data_startPos/100*(scrollPaneWidth-scrollContentWidth))+'px');}else{scrollContent.css('margin-left',0);}scrollbar.find('.ui-slider-handle').css({width:'60px',marginLeft:'-30px'});}function createContent(game){var gameSlider=$('.game-slider'),gameContent=$('.game-content'),gameContentMain=$('.game-content-main'),gameContentLoader=$('.loader');if(gameContent.length){gameContent.animate({opacity:0,},150);}else{gameSlider.after('<div class="game-content-main" style="height: 0; position: relative"><div class="loader" style="opacity: 0"/><div class="game-content"></div></div>');gameContentMain=$('.game-content-main');gameContent=$(
'.game-content');gameContentLoader=$('.loader');var targetHeight=gameContent.outerHeight();gameContentMain.animate({height:targetHeight},100);}if(gameContentLoader.length){gameContentLoader.animate({opacity:1,},250);}var api=new mw.Api();api.get({action:'parse',format:'json',text:'{{'+data_template+'|'+game+'}}'}).done(function(data){if(!data.error){var code=data.parse.text['*'];if(gameContentLoader.length){gameContentLoader.animate({opacity:0,},100);}gameContent.html(code);createContentSlider();gameContent.animate({opacity:1,},150);}});}$(function(){var gameSlider=$('.game-slider');if(!gameSlider.length)return;$('head').append('<link rel="stylesheet" href="https://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />');importArticle({type:"style",article:"u:dev:MediaWiki:GameSlider.css"});gameSlider.wrap('<div class="scroll-pane"></div>').addClass('scroll-content').before('<div class="scroll-bar-wrap ui-widget-content"><div class="scroll-bar"></div></div>');mediaWiki.loader.using(
'jquery.ui.slider',function(){$('.scroll-pane').each(createSlider);});});}());function createContentSlider(){mw.loader.using(['jquery.cookie']);mw.loader.using(['jquery.ui.tabs'],function(){$("[class^=portal_vtab]").tabs().addClass("ui-tabs-vertical ui-helper-clearfix");var $tabs=$("#portal_slider").tabs({fx:{opacity:'toggle',duration:100}});$("[class*=portal_sliderlink-]").click(function(){$tabs.tabs('select',this.className.match(/portal_sliderlink-(\d+)/)[1]);return false;});$(".game-content .ui-corner-all").removeClass("ui-corner-all");$(".game-content .ui-corner-left").removeClass("ui-corner-left");$(".game-content .ui-corner-right").removeClass("ui-corner-right");$(".game-content .ui-corner-top").removeClass("ui-corner-top");$(".game-content .ui-corner-bottom").removeClass("ui-corner-bottom");$(".game-content .ui-widget-content").removeClass("ui-widget-content");});}function defaultValue(variable,defaultVal){if(variable!==undefined&&variable!==null)return variable;return defaultVal
;};mw.hook('wikipage.content').add(function($content){$content.find('.youtubeplayer:not(.loaded)').each(function(){var $this=$(this),data=$this.data(),uri=new mw.Uri('https://www.youtube.com/embed/'),id=String(data.id||'').trim(),loop=String(data.loop||'').trim();if(id===''){console.warn('[YoutubePlayer] Video ID is not defined.');return;}uri.path+=id;uri.query={autoplay:window.YoutubePlayerDisableAutoplay?'0':String(data.autoplay||'').trim(),loop:loop,playlist:loop==='1'?id:'',start:String(data.start||'').trim(),list:String(data.list||'').trim()};$this.html($('<iframe>',{width:String(data.width||'').trim(),height:String(data.height||'').trim(),src:uri.toString(),allowfullscreen:'true',allow:'fullscreen'+(loop?'; autoplay':'')})).addClass('loaded');});});;require([require.optional('ext.wikia.design-system.loading-spinner'),'jquery','mw',require.optional('wikia.tracker'),'wikia.window'],function(Spinner,$,mw,tracker,window){if(window.helpPanelLoaded){return;}window.helpPanelLoaded=!0;
var HelpPanel={config:mw.config.get(['wgIsEditPage','wgSassParams','wgSiteName','wgUserId','wgUserName']),helpPages:['general-editing-help','infoboxes','adding-images','adding-links','source-editor'],loading:3,preload:function(){if(--this.loading===0){window.dev.i18n.loadMessages('u:dev:MediaWiki:Custom-InEditorHelp/i18n.json').then($.proxy(this.init,this));}},isNewUser:function(){var self=this;return new $.Deferred(function(deferred){if(self.config.wgUserId===null){deferred.resolve(true);return;}var cache=localStorage.getItem('HelpPanel-newUser');if(cache===false||(cache!==null&&Date.now()-parseInt(cache)<900000)){deferred.resolve(cache!==false);return;}new mw.Api().get({action:'query',meta:'userinfo',uiprop:'editcount'}).done(function(r){var newUser=r.error||r.query.userinfo.editcount<25;deferred.resolve(newUser);localStorage.setItem('HelpPanel-newUser',newUser?Date.now():false);});});},init:function(i18n){this.i18n=i18n;this.addCSS();this.addTracking();this.ipPromise=this.config.
wgUserName?$.Deferred().resolve():this.fetchIP();var self=this;this.isNewUser().done(function(newUser){if(!newUser)return;if(self.config.wgIsEditPage){self.initEditor();}else{mw.hook('ve.activate').add($.proxy(self.initEditor,self));mw.hook('ve.deactivationComplete').add($.proxy(self.destroyVisualEditor,self));}});},addCSS:function(){var background=$('#EditPage').css('background-color');if(!$('#EditPage').exists()){background=$('.WikiaPage .WikiaPageBackground').css('background-color');}mw.util.addCSS('html {'+'--helpPanel-bgcolor:'+background+';'+'--helpPanel-header-bgcolor:'+this.config.wgSassParams['color-header']+';'+'}');},fetchIP:function(){return $.get(mw.util.wikiScript('api'),{action:'query',meta:'userinfo',format:'json'});},togglePanelOpen:function(){$('#helpPanelCTA').hide();$('#helpPanel').toggleClass('hideHelpPanel').toggleClass('showHelpPanel');},togglePanelClose:function(){$('#helpPanel').toggleClass('hideHelpPanel').toggleClass('showHelpPanel');$('#helpPanelCTA').show()
;},closeNotification:function(){$('#helpPanelCTA').hide();},submitPost:function(){if($('#hp-forum-textarea').val()===''){$('#helpPanel-forum .error-msg').css('display','block');return;}$.ajax({type:'POST',url:'https://'+this.i18n.msg('community-wiki-url').plain()+'/wikia.php?'+$.param({controller:'WallExternal',method:'postNewMessage',format:'jsonp'}),data:{body:$('#hp-forum-textarea').val()+($('#helpPanel-check').attr('checked')==='checked'?('\n\n\n'+new mw.Uri(mw.util.getUrl()).toString()):''),messagetitle:$('#helpPanel-check').attr('checked')=='checked'?this.i18n.msg('need-help-on',this.config.wgSiteName).plain():this.i18n.msg('need-help').plain(),pagenamespace:2000,pagetitle:this.i18n.msg('forum-board').plain(),token:mw.user.tokens.get('editToken')},xhrFields:{withCredentials:!0},complete:$.proxy(this.checkPost,this)});$('#helpPanel-spinner').addClass('show');$('#helpPanel-forum .error-msg').css('display','none');},checkPost:function(){$.ajax({type:'GET',url:'https://'+this.i18n.
msg('community-wiki-url').plain()+'/api.php',data:{action:'query',list:'usercontribs',ucuser:this.config.wgUserName||this.ip,ucnamespace:2001,ucprop:'ids',uclimit:1,format:'json'},dataType:'jsonp',success:$.proxy(this.submittedPost,this),error:$.proxy(this.submittedFail,this)});},submittedPost:function(data){if(data.query.usercontribs.length===0||new Date(data.query.usercontribs[0].timestamp)<new Date()-60*60*1000){return this.submittedFail(data);}$('#helpPanel-post-link').attr('href','https://'+this.i18n.msg('community-wiki-url').plain()+'/wiki/Thread:'+data.query.usercontribs[0].pageid);$('#helpPanel-spinner').removeClass('show');$('#hp-step3').addClass('showHP-step').removeClass('hideHP-step');$('#hp-step1, #hp-step2').addClass('hideHP-step').removeClass('showHP-step');},submittedFail:function(data){console.error(data);},toggleStep1:function(){$('#hp-step1').addClass('showHP-step').removeClass('hideHP-step');$('#hp-step2, #hp-step3').addClass('hideHP-step').removeClass('showHP-step'
);},toggleStep2:function(){$('#hp-step2').addClass('showHP-step').removeClass('hideHP-step');$('#hp-step1, #hp-step3').addClass('hideHP-step').removeClass('showHP-step');},done:function(){$('#hp-forum-textarea').val('');this.toggleStep1();},waitForIP:function(){this.ipPromise.then($.proxy(this.gotIP,this));},gotIP:function(data){if(this.config.wgUserName){$('#helpPanel-post-text').html(this.i18n.msg('ask-intro',this.i18n.msg('username').plain(),this.config.wgUserName).parse());}else{this.ip=data.query.userinfo.name;$('#helpPanel-post-text').html(this.i18n.msg('ask-intro',this.i18n.msg('ip').plain(),this.ip).parse());}$('#hp-step2').addClass('showHP-step').removeClass('hideHP-step');$('#hp-step1, #hp-step3').addClass('hideHP-step').removeClass('showHP-step');},initEditor:function(){if(!$('#WikiaNotifications').exists()){var notifications=window.dev.ui({type:'ul',attr:{id:'WikiaNotifications'},classes:['WikiaNotifications']});if($('#WikiaBar').exists()){$('#WikiaBar').append(
notifications);}else{$(document.body).append(notifications);}}$('#WikiaNotifications').append(window.dev.ui({type:'li',children:[{type:'div',attr:{id:'helpPanelCTA',},children:[{type:'p',text:this.i18n.msg('get-help').plain(),events:{click:$.proxy(this.togglePanelOpen,this)},},{type:'a',classes:['sprite','close-notification'],events:{click:$.proxy(this.closeNotification,this)},data:{tracking:'CTA-close'}}]}]}),window.dev.ui({type:'div',attr:{id:'helpPanel',},classes:['hideHelpPanel'],children:[{type:'div',attr:{id:'helpPanel-spinner'},html:Spinner?new Spinner(38,2).html.replace('wds-block','wds-spinner__block').replace('wds-path','wds-spinner__stroke'):''},{type:'div',classes:['helpPanel-close'],events:{click:$.proxy(this.togglePanelClose,this)},children:[window.dev.wds.icon('close')],data:{tracking:'CTA-close'}},{type:'div',classes:['helpPanel-contents'],children:[this.renderStepOne(),this.renderStepTwo(),this.renderStepThree()]}]}));mw.hook('HelpPanel.ui').fire();},renderStepOne:
function(){return{type:'div',attr:{id:'hp-step1'},classes:['showHP-step'],children:[{type:'div',attr:{id:'helpPanelHead'},children:[{type:'div',classes:['helpPanel-question'],children:[window.dev.wds.icon('question')],},{type:'h3',text:this.i18n.msg('get-help2').plain()}]},{type:'div',attr:{id:'helpPanel-main'},children:[{type:'h4',text:this.i18n.msg('top-help-pages').plain()},{type:'ul',children:this.helpPages.map(this.mapHelpPage,this)},{type:'p',children:[this.mapHelpPage('more-help-articles')]}]},{type:'div',attr:{id:'helpPanel-forum'},children:[{type:'div',html:this.i18n.msg('not-here').parse()},{type:'div',attr:{id:'helpPanel-buttons'},children:[{type:'button',classes:['wikia-button'],data:{tracking:'ask-on-forum'},events:{click:$.proxy(this.waitForIP,this)},text:this.i18n.msg('ask').plain()}]}]}]};},renderStepTwo:function(){return{type:'div',attr:{id:'hp-step2'},children:[{type:'div',attr:{id:'helpPanelHead'},children:[{type:'div',classes:['helpPanel-question'],children:[window.
dev.wds.icon('question')]},{type:'h3',text:this.i18n.msg('ask').plain()}]},{type:'div',attr:{id:'helpPanel-main'},children:[{type:'p',attr:{id:'helpPanel-post-text'}}]},{type:'div',classes:['helpPanel-forumForm'],attr:{id:'helpPanel-forum'},children:[{type:'p',html:this.i18n.msg(this.config.wgUserName?'reply-info':'reply-info-anon').parse().replace('$1',window.dev.wds.icon('message').outerHTML),},{type:'h4',text:this.i18n.msg('ask-header').plain()},{type:'div',text:this.i18n.msg('question-error').plain(),classes:['error-msg']},{type:'textarea',attr:{id:'hp-forum-textarea',tabindex:'0',data:{tracking:'post-done'},'aria-disabled':'false',rows:'3',placeholder:this.i18n.msg('ask-placeholder').plain()}},{type:'input',attr:{type:'checkbox',id:'helpPanel-check',name:'include-title',checked:'checked'}},{type:'label',attr:{'for':'helpPanel-check'},text:this.i18n.msg('include-title').plain()},{type:'div',attr:{id:'helpPanel-buttons'},children:[{type:'button',classes:['wikia-button','secondary'],
text:this.i18n.msg('back').plain(),data:{tracking:'forum-question-back'},events:{click:$.proxy(this.toggleStep1,this)}},{type:'button',classes:['wikia-button'],text:this.i18n.msg('submit').plain(),data:{tracking:'forum-question-submitted'},events:{click:$.proxy(this.submitPost,this)}}]}]}]};},renderStepThree:function(){return{type:'div',attr:{id:'hp-step3'},children:[{type:'div',attr:{id:'helpPanelHead'},children:[{type:'div',classes:['helpPanel-question'],children:[window.dev.wds.icon('question')]},{type:'h3',text:this.i18n.msg('ask').plain()}]},{type:'div',attr:{id:'helpPanel-main'},children:[{type:'h4',children:[{type:'span',children:[window.dev.wds.icon('checkmark')]},{type:'span',classes:['successmsg'],text:this.i18n.msg('success-header').plain()}]},{type:'p',text:this.i18n.msg('success-message-intro').plain()},{type:'p',html:this.i18n.msg(this.config.wgUserName?'success-message':'success-message-anon').parse().replace('$1',window.dev.wds.icon('message').outerHTML),},{type:'p',
children:[{type:'a',attr:{href:'#',id:'helpPanel-post-link',target:'_blank'},data:{tracking:'post-link'},text:this.i18n.msg('forum-link').plain()}]}]},{type:'div',attr:{id:'helpPanel-forum'},children:[{type:'div',attr:{id:'helpPanel-buttons'},children:[{type:'button',classes:['wikia-button'],attr:{'aria-diabled':'false',tabindex:'0',},text:this.i18n.msg('done').plain(),events:{click:$.proxy(this.done,this)}}]}]}]};},mapHelpPage:function(page){var linkMsg=page==='general-editing-help'?this.config.wgIsEditPage?'classic-page':'visual-page':page+'-page';return{type:'li',children:[{type:'a',attr:{href:mw.util.getUrl(this.i18n.inContentLang().msg(linkMsg).plain()),target:'_blank',title:page},classes:['helpPanel-help-page-link'],text:this.i18n.msg(page).plain()}]};},destroyVisualEditor:function(){$('#helpPanelCTA').remove();},track:function(action,label,args){tracker.track($.extend({trackingMethod:'analytics',category:'help-panel',action:action,label:label+(this.config.wgUserName?'':'-anon')}
,args));},addTracking:function(){if(!tracker){return;}this.track(tracker.ACTIONS.VIEW,'editor-loaded',{noninteraction:!0});$('body').on('click','#helpPanelCTA',$.proxy(this.trackOpenModal,this)).on('click','#helpPanel .helpPanel-close',$.proxy(this.trackCloseModal,this)).on('click','#helpPanel [data-tracking]',$.proxy(this.trackButtonClick,this)).on('click','#helpPanel .helpPanel-help-page-link',$.proxy(this.trackHelpPageClick,this));},trackOpenModal:function(){this.track(tracker.ACTIONS.CLICK,'toggle-panel-open');},trackCloseModal:function(){this.track(tracker.ACTIONS.CLICK,'toggle-panel-close');},trackButtonClick:function(event){this.track(tracker.ACTIONS.CLICK,'button-'+$(event.target).attr('data-tracking'));},trackHelpPageClick:function(event){this.track(tracker.ACTIONS.CLICK,'article-'+$(event.target).attr('title'));}};mw.hook('dev.ui').add($.proxy(HelpPanel.preload,HelpPanel));mw.hook('dev.i18n').add($.proxy(HelpPanel.preload,HelpPanel));mw.hook('dev.wds').add($.proxy(HelpPanel
.preload,HelpPanel));importArticles({type:'script',articles:['u:dev:MediaWiki:I18n-js/code.js','u:dev:MediaWiki:UI-js/code.js','u:dev:MediaWiki:WDSIcons/code.js']},{type:'style',articles:['u:dev:MediaWiki:InEditorHelp.css']});});;;mw.loader.state({"wikia.fake.articles.95cd4045aaa5699ac9d538452c92aa05":"ready"});

/* cache key: esdrama:resourceloader:filter:minify-js:7:1da8b8e35fbcdc00a41a471bca58a183 */