(function(){var SambaTV=window.SambaTV=window.SambaTV||[];SambaTV.attrs||(SambaTV.attrs={});var serial=function(obj){var str=[];for(var p in obj)
if(obj.hasOwnProperty(p)){str.push(encodeURIComponent(p)+"="+encodeURIComponent(obj[p]));}
return str.join("&");}
if(!Array.prototype.indexOf){Array.prototype.indexOf=function(obj,start){for(var i=(start||0),j=this.length;i<j;i++){if(this[i]===obj){return i;}}
return-1;};}
var send_request=function(url,cb,load_evt_name){try{if(window.XDomainRequest&&window.navigator.appVersion.indexOf("MSIE 10.0")==-1){var xdr=new XDomainRequest();xdr.open("GET",url);xdr.onprogress=function(){};xdr.ontimeout=function(){};xdr.onerror=function(){};xdr.onload=function(){cb({'target':xdr});}
SambaTV.xhr_pending=true;setTimeout(function(){xdr.send();},0);}else{var xhr=new XMLHttpRequest();xhr.open("GET",url);xhr.addEventListener(load_evt_name,cb);SambaTV.xhr_pending=true;xhr.send();}}catch(err){}};var baseurl="https://pixel.mtrcs.samba.tv/v2/tag/wikia/fandom-homepage";var domload_cb=function(event){try{if(typeof utag_data!=='undefined'){SambaTV.attrs.sa_puid=utag_data.shopperid;SambaTV.attrs.cust_stat=utag_data.ret_customer_type;}
var combined_attrs={};var base_attrs={sa_referrer:window.document.referrer,sa_fullurl:window.location.toString(),c:''+(new Date().getTime())};for(each in SambaTV.attrs){combined_attrs[each]=SambaTV.attrs[each];}
for(each in base_attrs){combined_attrs[each]=base_attrs[each];}
SambaTV.attrs_paramstr=serial(combined_attrs);var load_url=baseurl+'/load'+"?"+SambaTV.attrs_paramstr;SambaTV.evt_targets={impression:[],purchase:[],click:[],register:[],login:[]};send_request(load_url,init_load_cb,'load');}catch(err){}}
var init_load_cb=function(event){try{SambaTV.xhr_pending=false;SambaTV.evt_targets=JSON.parse(event.target.responseText);SambaTV.push_targets(SambaTV.evt_targets['impression'].slice());SambaTV.consume_target_q();}catch(err){}};window.setTimeout(domload_cb,0);SambaTV.target_q=[];SambaTV.push_target=function(target_obj){SambaTV.xhr_pending?null:SambaTV.consume_target_q();SambaTV.target_q.push(target_obj);};SambaTV.push_targets=function(target_obj_list,evt_atts){evt_atts=evt_atts||{};SambaTV.xhr_pending?null:window.setTimeout(SambaTV.consume_target_q,0);for(var i=0;i<target_obj_list.length;i++){target_obj_list[i].evt_atts=evt_atts;SambaTV.target_q.push(target_obj_list[i]);}};SambaTV.consume_target_q=function(){if(SambaTV.target_q.length){SambaTV.consume_target_one()}};SambaTV.consume_target_one=function(){try{var tgt=SambaTV.target_q.splice(0,1)[0];var evt_attstr,tgt_url;if(tgt.evt_atts&&tgt.passthru){evt_attstr=SambaTV.attrs_paramstr+"&"+serial(tgt.evt_atts);}else if(tgt.passthru){evt_attstr=SambaTV.attrs_paramstr;}else if(tgt.evt_atts){evt_attstr=serial(tgt.evt_attstr)}else{evt_attstr='';}
if(tgt.url.indexOf("?")===-1){tgt_url=tgt.url+"?"+evt_attstr;}else{tgt_url=tgt.url+"&"+evt_attstr;}
if(tgt.type==='xhr'){send_request(tgt_url,SambaTV.target_xhr_cb,'loadend')}else if(tgt.type==='image'){var px=new Image(0,0);SambaTV.xhr_pending=true;px.onload=SambaTV.target_xhr_cb;px.onerror=SambaTV.target_xhr_cb;px.src=tgt_url;}}catch(err){}}
SambaTV.target_xhr_cb=function(event){SambaTV.xhr_pending=false;SambaTV.consume_target_q();}
SambaTV.Impression=function(atts){var combined_attrs={};var base_attrs={sa_referrer:window.document.referrer,sa_fullurl:window.location.toString(),c:''+(new Date().getTime())};for(each in SambaTV.attrs){combined_attrs[each]=SambaTV.attrs[each];}
for(each in base_attrs){combined_attrs[each]=base_attrs[each];}
SambaTV.attrs_paramstr=serial(combined_attrs);SambaTV.push_targets(SambaTV.evt_targets['impression'].slice(),atts);};SambaTV.Purchase=function(atts){SambaTV.push_targets(SambaTV.evt_targets['purchase'].slice(),atts);};SambaTV.Register=function(atts){};SambaTV.Click=function(atts){SambaTV.push_targets(SambaTV.evt_targets['click'].slice(),atts);};SambaTV.Login=function(atts){SambaTV.push_targets(SambaTV.evt_targets['login'].slice(),atts);};SambaTV.Register=function(atts){SambaTV.push_targets(SambaTV.evt_targets['register'].slice(),atts);};SambaTV.track=function(){};})();